version: '3.8'

volumes:
  postgres:

services:
  # database:
  #   container_name: database
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - postgres:/var/lib/postgresql/data:delegated
  #   ports:
  #     - 5432:5432

  api:
    container_name: api
    build: .
    restart: always
    ports:
      - 8000:8000
